### ISSUE TITLE
token-vault steal crashes the beacon

### ISSUE THREAD

**Issue by CodeXTF2** [Henkru/cs-token-vault#1]
![image](https://user-images.githubusercontent.com/29991665/184594651-7bfbc8a6-bf3e-49e0-963e-043007b413b7.png)

**Comment by Henkru** [comment]
Hi,

Did you use the exact vault id from the `create` command? Since the id is used as a direct memory address for the vault.

Could you provide the full beacon log and the exact versions of CS and victim's Windows?

**Comment by CodeXTF2** [comment]
Yes, I did. Yeah il post the log in a sec

**Comment by CodeXTF2** [comment]
```
beacon> token-vault create
[*] Token Vault - create (@henkru)
[+] host called home, sent: 3425 bytes
[+] received output:
token vault created: 000002C53D2C2570
[+] host called home, sent: 12 bytes
beacon> token-vault set 000002C53D2C2570
beacon> token-vault steal 11572
[*] Token Vault - steal (@henkru)
[+] host called home, sent: 3439 bytes
*beacon crash*
```

**Comment by CodeXTF2** [comment]
CS 4.5, Windows 10 19044.1889

**Comment by Henkru** [comment]
Thanks, and is it x64? I'll try reproduce this when I'm back from my trip. In meanwhile, can you try with the latest CS version (4.6.1)?

If I'm not able to get the crash, I'll provide a debug build which gives some additional info to pinpoint to issue (if this is fine for you).

**Comment by CodeXTF2** [comment]
ye that works. I dont think CS version matters here, since 4.6.1 is just a licensing change for the most part.
edit: yeah its x64

**Comment by nowhey2** [comment]
If it helps any, I am observing the same problems and am using 4.6.1.  All systems are x64. Crashes occurring in win10/server 2016.

From the win10 system
`Faulting application name: upnpcont.exe, version: 10.0.19041.867, time stamp: 0x35d3e1a5
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x0000020ab94b2c9d
Faulting process id: 0x4584
Faulting application start time: 0x01d8b190ebd79c4d
Faulting application path: C:\WINDOWS\system32\upnpcont.exe
Faulting module path: unknown
Report Id: 342fb590-e6f0-4b5e-bf11-0ced2d0a1f18
Faulting package full name: 
Faulting package-relative application ID: `

`Host Name:                 WKSTN-003
OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.19042 N/A Build 19042
OS Manufacturer:           Microsoft Corporation`

**Comment by Henkru** [comment]
Could you test with the latest [release](https://github.com/Henkru/cs-token-vault/releases/tag/v0.2).

The root case was 32 vs. 64-bit Java (looks like, Java's Windows installer installs 32-bit version by default...)  Behaviour of [`bof_pack`](https://hstechdocs.helpsystems.com/manuals/cobaltstrike/current/userguide/content/topics_aggressor-scripts/as-resources_functions.htm#bof_pack)  differs between architectures.

**Comment by CodeXTF2** [comment]
Will test once im free, will update u tmw latest

**Comment by CodeXTF2** [comment]
Nope, same issue.

**Comment by Henkru** [comment]
It seems that Sleep is able to surprise me again. I found the root case but to make sure, can you test it with the following files, and post the output. The `steal` command just prints the received address, so it _should_ not crash the beacon in any case.
[token-vault-dbg.zip](https://github.com/Henkru/cs-token-vault/files/9372388/token-vault-dbg.zip)

**Comment by CodeXTF2** [comment]
```
beacon> token-vault create
[*] Token Vault - create (@henkru)
[+] host called home, sent: 3661 bytes
[+] received output:
Command: 4 1
[+] received output:
token vault created: 00000235D4032570
beacon> token-vault set 00000235D4032570
beacon> token-vault steal 10516
[*] Token Vault - steal (@henkru)
[+] host called home, sent: 3675 bytes
[+] received output:
Command: 18 2
[+] received output:
a1: D4032570
[+] received output:
a2: 235
[+] received output:
vault: 00000234D4032570
[+] received output:
number of pids: 1
```
Sleep do be like that, it gave me hell trying to parse JSON once lol

**Comment by Henkru** [comment]
Thanks, that is looking the correct output. Here is the latest version with the steal function enabled.

[token-vault.zip](https://github.com/Henkru/cs-token-vault/files/9372871/token-vault.zip)

**Comment by CodeXTF2** [comment]
Works! Thx for the fix!

**Comment by Henkru** [comment]
Perfect, thanks for taking the time to help debugging the issue.
